version: 0.2

phases:
  install:
    commands:
      - echo installing node 14 and npm...
      - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo installing app dependencines...
      - npm install
  build:
    commands:
      - echo building...
      - npm run build
      - echo invalidating cloudfront cache
      - npm run cloudfront-invalidation
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build