export const LOAD_SUMMONER_SUCCESS = "LOAD_SUMMONER_SUCCESS";
export const LOAD_MATCH_LIST_SUCCESS = "LOAD_MATCH_LIST_SUCCESS";
export const LOAD_SUMMONER_RANK_SUCCESS = "LOAD_SUMMONER_RANK_SUCCESS";
export const LOAD_SUMMONER_MATCH_INFO_SUCCESS =
  "LOAD_SUMMONER_MATCH_INFO_SUCCESS";
export const LOAD_LOL_LEADERBOARDS_SUCCESS = "LOAD_LOL_LEADERBOARDS_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
