import * as Champions from "../assets/images/index";
import shib from "../components/leagueResults/shib_coin.png";

export function getChampion(name) {
  switch (name) {
    case "Ahri":
      return Champions.Ahri;
    case "Aatrox":
      return Champions.Aatrox;
    case "Akali":
      return Champions.Akali;
    case "Alistar":
      return Champions.Alistar;
    case "Amumu":
      return Champions.Amumu;
    case "Anivia":
      return Champions.Anivia;
    case "Annie":
      return Champions.Annie;
    case "Ashe":
      return Champions.Ashe;
    case "AurelionSol":
      return Champions.AurelionSol;
    case "Azir":
      return Champions.Azir;
    case "Bard":
      return Champions.Bard;
    case "Blitzcrank":
      return Champions.Blitzcrank;
    case "Braum":
      return Champions.Braum;
    case "Brand":
      return Champions.Brand;
    case "Caitlyn":
      return Champions.Caitlyn;
    case "Cassiopeia":
      return Champions.Cassiopeia;
    case "Camille":
      return Champions.Camille;
    case "Chogath":
      return Champions.Chogath;
    case "Corki":
      return Champions.Corki;
    case "Darius":
      return Champions.Darius;
    case "Diana":
      return Champions.Diana;
    case "Draven":
      return Champions.Draven;
    case "DrMundo":
      return Champions.DrMundo;
    case "Ekko":
      return Champions.Ekko;
    case "Elise":
      return Champions.Elise;
    case "Evelyn":
      return Champions.Evelynn;
    case "Ezreal":
      return Champions.Ezreal;
    case "Fiddlesticks":
      return Champions.Fiddlesticks;
    case "Fiora":
      return Champions.Fiora;
    case "Fizz":
      return Champions.Fizz;
    case "Galio":
      return Champions.Galio;
    case "Gangplank":
      return Champions.Gangplank;
    case "Garen":
      return Champions.Garen;
    case "Gnar":
      return Champions.Gnar;
    case "Gragas":
      return Champions.Gragas;
    case "Graves":
      return Champions.Graves;
    case "Hecarim":
      return Champions.Hecarim;
    case "Heimerdinger":
      return Champions.Heimerdinger;
    case "Illaoi":
      return Champions.Illaoi;
    case "Irelia":
      return Champions.Irelia;
    case "Ivern":
      return Champions.Ivern;
    case "Janna":
      return Champions.Janna;
    case "Jax":
      return Champions.Jax;
    case "Jayce":
      return Champions.Jayce;
    case "Jhin":
      return Champions.Jhin;
    case "Jinx":
      return Champions.Jinx;
    case "Kalista":
      return Champions.Kalista;
    case "Karma":
      return Champions.Karma;
    case "Karthus":
      return Champions.Karthus;
    case "Kassadin":
      return Champions.Kassadin;
    case "Katarina":
      return Champions.Katarina;
    case "Kayle":
      return Champions.Kayle;
    case "Kennen":
      return Champions.Kennen;
    case "Khazix":
      return Champions.Khazix;
    case "Kindred":
      return Champions.Kindred;
    case "Kled":
      return Champions.Kled;
    case "KogMaw":
      return Champions.KogMaw;
    case "Leblanc":
      return Champions.Leblanc;
    case "LeeSin":
      return Champions.LeeSin;
    case "Leona":
      return Champions.Leona;
    case "Lissandra":
      return Champions.Lissandra;
    case "Lucian":
      return Champions.Lucian;
    case "Lulu":
      return Champions.Lulu;
    case "Lux":
      return Champions.Lux;
    case "Malphite":
      return Champions.Malphite;
    case "Malzahar":
      return Champions.Malzahar;
    case "Maokai":
      return Champions.Maokai;
    case "MasterYi":
      return Champions.MasterYi;
    case "MissFortune":
      return Champions.MissFortune;
    case "MonkeyKing":
      return Champions.MonkeyKing;
    case "Mordekaiser":
      return Champions.Mordekaiser;
    case "Morgana":
      return Champions.Morgana;
    case "Nami":
      return Champions.Nami;
    case "Nasus":
      return Champions.Nasus;
    case "Nidalee":
      return Champions.Nidalee;
    case "Nocturne":
      return Champions.Nocturne;
    case "Nunu":
      return Champions.Nunu;
    case "Olaf":
      return Champions.Olaf;
    case "Orianna":
      return Champions.Orianna;

    case "Pantheon":
      return Champions.Pantheon;
    case "Poppy":
      return Champions.Poppy;
    case "Quinn":
      return Champions.Quinn;
    case "Rammus":
      return Champions.Rammus;
    case "RekSai":
      return Champions.RekSai;
    case "Renekton":
      return Champions.Renekton;
    case "Rengar":
      return Champions.Rengar;
    case "Riven":
      return Champions.Riven;
    case "Rumble":
      return Champions.Rumble;
    case "Ryze":
      return Champions.Ryze;
    case "Sejuani":
      return Champions.Sejuani;
    case "Shaco":
      return Champions.Shaco;
    case "Shen":
      return Champions.Shen;
    case "Shyvana":
      return Champions.Shyvana;
    case "Singed":
      return Champions.Singed;
    case "Sion":
      return Champions.Sion;
    case "Sivir":
      return Champions.Sivir;
    case "Skarner":
      return Champions.Skarner;
    case "Sona":
      return Champions.Sona;
    case "Soraka":
      return Champions.Soraka;
    case "Swain":
      return Champions.Swain;
    case "Syndra":
      return Champions.Syndra;
    default:
      return shib;
  }
}
